FROM docker.io/library/nginx

LABEL maintainer="Khaing Min <khaingmin.pmn@gmail.com>"

COPY ./configure-api.sh /docker-entrypoint.d/
COPY resources /usr/share/nginx/html/resources
COPY ./index.html /usr/share/nginx/html/ 
