FROM docker.io/library/python:alpine

LABEL maintainer="Khaing Min <khaingmin.pmn@gmail.com>"

WORKDIR /web

COPY run-http.sh /web
COPY resources /web/html/resources
COPY index.html /web/html/ 

CMD ["/web/run-http.sh"]

