FROM docker.io/library/golang AS builder 

LABEL maintainer="Khaing Min <khaingmin.pmn@gmail.com>"

WORKDIR /go/src

COPY todo-api.go .

RUN go mod init todoapp/todo-api && \ 
    go mod tidy && \ 
    go build

FROM registry.access.redhat.com/ubi8-micro

WORKDIR /app
COPY --from=builder /go/src/todo-api /app

CMD ["/app/todo-api"]
